### PR TITLE
exhaustive map values

### LINKED ISSUE #66: Check exhaustiveness of map values in addition to keys
My use case is to define an ACL layer that needs to map both to and from domain enums to external values.

```go
type ContactPreference string

const (
	ContactPreferenceMobile ContactPreference = "MOBILE"
	ContactPreferenceHome   ContactPreference = "HOME"
	ContactPreferenceMail   ContactPreference = "MAIL"
	ContactPreferenceNone   ContactPreference = ""
)

var fromContactPreferenceMap = map[ContactPreference]string{
	ContactPreferenceMobile: "mobilePhone",
	ContactPreferenceHome:   "homePhone",
	ContactPreferenceMail:   "physicalMail",
	ContactPreferenceNone:   "",
}

var toContactPreferenceMap = map[string]ContactPreference{
	"mobilePhone":  ContactPreferenceMobile,
	"homePhone":    ContactPreferenceHome,
	"physicalMail": ContactPreferenceMail,
	"":             ContactPreferenceNone,
}

func toContactPreference(cp string) ContactPreference {
	if contactPref, ok := toContactPreferenceMap[cp]; ok {
		return contactPref
	}

	return ContactPreferenceNone
}

func fromContactPreference(cp ContactPreference) string {
	return fromContactPreferenceMap[cp]
}
```

In the above example, `fromContactPreferenceMap` **will** be checked for exhaustive use of `ContactPreference` because it's the **keys** of the map.
However, `toContactPreferenceMap` **will not** be checked for exhaustiveness because `ContactPreference` is the **values** in the map.

### PR DESCRIPTION
**Pull request by dillonstreator**
fixes #66

### CODE REVIEW

**Comment by ImprintNav** [comment]
This behavior isn't always desirable. One situation I've run into is when you're trying to project a set of enums of type `A` into a set of enums of type `B` where the number of elements in `A` is smaller than the number of elements in `B`. Then it becomes impossible to satisfy everything in `B`. Not to mention this is a backwards incompatible change.

I feel like this needs to be gated by a flag or some special enforcement comment.

**Comment by dillonstreator** [comment]
Fair point @ImprintNav - you could ignore those cases which seem to be a bit more edge case. `exhaustive` has not reached a stable major version so from a semver standpoint, there isn't any reason a breaking change couldn't be introduced. I do agree however that introducing this as an opt-in would be much friendlier to clients. Maybe whenever v1 is released, this could be a default.

@nishanths do you have any thoughts one way or the other?

**Comment by NavneethJayendran** [comment]
@dillonstreator in those situations, I still wanted to enforce exhaustiveness checks on the keys, just not the values. An `exhaustive:enforce,values` directive would be much friendlier.

Another option is to skip the values check when both keys and values are enums and the values enum cardinality is higher than the keys enum cardinality.

**Comment by dillonstreator** [comment]
Closing due to https://github.com/nishanths/exhaustive/issues/66#issuecomment-1732338328

If a use case presents itself where this functionality is desired, we can reopen or use this PR as a framework for adding the functionality in a more opt-in fashion.

**Comment by dillonstreator** [comment]
Closing due to https://github.com/nishanths/exhaustive/issues/66#issuecomment-1732338328

If a use case presents itself where this functionality is desired, we can reopen or use this PR as a framework for adding the functionality in a more opt-in fashion.

**Pull request closed without merging**
