### PR TITLE
validate map keys the same way as switch cases

### LINKED ISSUE #35: Validate `map` keys the same way as `switch` cases
There are places when we need to convert enum to some different value (enum or string, for example). 
Go's `map` is less verbose than `switch` and is more suitable for those cases.
Let's validate map keys with `exhaustive` linter.

Example
```go
type Enum int

const (
	A Enum = iota
	B
	C
)

func EnumToString_Switch(e Enum) string {
	switch e {
	case A:
		return "A"
	case B:
		return "B"
	case C:
		return "C"
	}
}

func EnumToString_Map(e Enum) string {
	return map[Enum]string{
		A: "A",
		B: "B",
		C: "C",
	}[e]
}
```

### PR DESCRIPTION
**Pull request by maratori**
Fix #35

In some cases `switch` by enum is too verbose and can be simplified by using `map`. WIth this PR `exhaustive` validates map keys as well.

```go
type Enum int

const (
	A Enum = iota
	B
	C
)

func EnumToString(e Enum) string {
	return map[Enum]string{
		A: "A",
		B: "B",
		C: "C",
	}[e]
}
```

### CODE REVIEW

**Comment by maratori** [comment]
@nishanths I've decided to not refactor code in this PR.
1. I'm not sure how would you like to do it
2. PR is huge even without refactoring (however the most changes are in tests)

**Comment by nishanths** [comment]
Thank you so much. I will review it this weekend.

**Comment by nishanths** [comment]
I looked at it quickly, and I couldn't find parts that would significantly benefit from refactoring right now, so I can think we can do it later if necessary. Did you have any parts in mind?

**Comment by maratori** [comment]
I don't have concrete suggestions for now. But here are some points of improvement:
- Following entities are declared in `switch.go`, but used in `map.go` as well:
  - `type nodeVisitor`
  - `const resultXXX`
  - `func diagnosticEnumTypeName`
  - `func diagnosticMissingMembers`
- Skipping generated files is duplicated in both `switchStmtChecker` and `mapChecker`
- `mapChecker` calls `analyzeCaseClauseExpr`

**Comment by nishanths** [comment]
Thank you, merged! And sorry for the delay. 

I will follow up with a commit to add `-maps` flag for checking maps, so users have a way to opt-in/opt-out of checking maps.

**Pull request merged**
